#! /usr/bin/env bash

echo "== delete object"

# Check for bucket name
if [ -z "$1" ]; then
    echo "No name provided. Please provide a name eg. ./bucket my-bucket-name."
    exit 1
fi


aws s3api list-objects-v2 \
--bucket $1 \
--query Contents[].Key \
| jq  -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects \
--bucket $1 \
--delete file:///tmp/delete_objects.json