#! /usr/bin/env bash

echo "== list objects"

# Check for bucket name
if [ -z "$1" ]; then
    echo "No name provided. Please provide a name eg. ./bucket my-bucket-name."
    exit 1
fi


aws s3api list-objects-v2 --bucket $1