#! /usr/bin/env bash

echo "== sync"

# Exit immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "No name provided. Please provide a bucket name eg. ./bucket my-bucket-name."
    exit 1
fi

# Check for file name
if [ -z "$2" ]; then
    echo "No name provided. Please provide a file name eg. ./bucket my-file-name."
    exit 1
fi

#where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove folder if it already exist
rm -r $OUTPUT_DIR

# lets create output folders
mkdir -p $OUTPUT_DIR


# Generate a random number to determine how many files to create
NUM_FILES=$((RANDOM % 6 * 5))

for ((i=1; i<$NUM_FILES; i++)); do
    # Generate a random filename

    FILENAME="$OUTPUT_DIR/$2_$i.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 * 1)) 2>/dev/null
done

tree $OUTPUT_DIR


aws s3 sync $OUTPUT_DIR s3://$1/files